"""empty message

Revision ID: 067d3baea5e5
Revises: 
Create Date: 2025-08-25 16:15:08.614328

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '067d3baea5e5'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(), nullable=True),
    sa.Column('data_nascimento', sa.Integer(), nullable=True),
    sa.Column('UF', sa.String(), nullable=True),
    sa.Column('email', sa.String(), nullable=True),
    sa.Column('senha', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
